# Generated by Django 4.1.7 on 2023-03-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='service',
            new_name='subject',
        ),
    ]
